version: '3.1'
services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: testdb
    ports:
      - "55432:5432" # Map PostgreSQL to localhost:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
